name: d05_notification_gcm_with_dart
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Your Name <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  pwa: 
    path: ../../pwa
#    git: 
#      url: https://github.com/kyorohiro/pwa.git
dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0

