name: d02_new_response_with_dart
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Your Name <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  service_worker: 
    git: 
      url: https://github.com/kyorohiro/service_worker.git

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
